[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "maine_state_legislator_data"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/maine_state_legislator_data" }
dependencies = [
    "beautifulsoup4==4.13.3",
    "requests==2.32.3",
    "tqdm==4.67.1",
]

[project.optional-dependencies]
dev = [
    "mypy==1.15.0",
    "pre-commit==4.2.0",
    "ruff==0.11.2",
    "types-beautifulsoup4==4.12.0.20250204",
    "types-requests==2.32.0.20250328",
    "types-tqdm==4.67.0.20250401"
]