name: Update CSV

on:
    schedule:
      - cron:  '0 9 1 * *'
    workflow_dispatch:

permissions: read-all

jobs:
    update-data:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write

        steps:
            - name: Harden runner
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf
              with:
                  disable-sudo: true
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

            - name: Set up Python 3.13
              uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
              with:
                  python-version: '3.13'
                  cache: pip

            - name: Install uv
              uses: install-pinned/uv@e25c5f1ccd69605d5bec5e481e4065f274d5438d

            - name: Install module and dependencies
              run: |
                  uv pip install --system -e .

            - name: Run src.main
              run: |
                  python -m src.main

            - name: Commit Changes
              uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79
              with:
                commit_message: Updated legislator data
